# Generated by Django 6.0.4 on 2026-05-07 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menucategory',
            options={'ordering': ('sort',), 'verbose_name_plural': 'Menu Categories'},
        ),
        migrations.AddField(
            model_name='menucategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('photo', models.ImageField(upload_to='dish_photos')),
                ('desc', models.CharField(max_length=500)),
                ('ingredients', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menucategory')),
            ],
            options={
                'verbose_name_plural': 'Dishes',
                'db_table': 'dishes',
                'ordering': ('sort',),
            },
        ),
    ]
